@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MzI0ODQ4MywianRpIjoiYTIxNzFmZDYtYmVlZS00Y2FlLThmZmMtZDU4ZDkwZGY4MDRlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3NjMyNDg0ODMsImNzcmYiOiJhNzhjMjc3MC0xYmRhLTQ0YzQtYTViZC0wOWFkOGEyNjc0OWIiLCJleHAiOjE3NjMyNDkzODN9.U3bOX1H_Z3ZMZ2N6q3ZBtd9kZV0r_ZLoHNlxzVoqFoU
@usuario_token = {{usuario_access_token}}

### teste 1

POST http://127.0.0.1:5000/api/register
Content-Type: application/json

{
"email": "funcionario@cupcakes.com",
"password": "senha456",
"is_admin": false
}
###
---

### teste 2 gerar token

POST http://127.0.0.1:5000/api/login
Content-Type: application/json

{
"email": "admin@cupcakes.com",
"password": "admin123"
}
###
---

### teste 3 verificar o token

GET http://127.0.0.1:5000/api/protected
Authorization: Bearer {{admin_token}}

### teste 4 (apos juntar o get e post no app.py)

POST http://127.0.0.1:5000/api/cupcakes
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
"nome": "Caramelo Salgado",
"descricao": "Cupcake cremoso de baunilha com recheio de caramelo salgado.",
"preco": 16.50,
"estoque": 10
}

### teste 5 deletar um ID de cupcake

DELETE http://127.0.0.1:5000/api/cupcakes/12
Authorization: Bearer {{admin_token}}